name: deploy-auth
# Controls when the workflow will run

# What events we are looking for
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # Only run this flow when make some changes inside the container
  push:
    branches:
      - master
    paths:
      - "packages/auth/**/*"

defaults:
  run:
    # Allows you to run this workflow manually from the Actions tab
    working-directory: "packages/auth"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # runs on Linux based VM
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #run a command
      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Upload to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/auth/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # invalidation - whenever we create new file in our S3 bucket that file
      # is going to be sent to cloudfront, however when we will update that file
      # cloudfront will not get automatically used of it, to get CLF use that file
      # we need to create invalidation and then CLF will update that file
      - name: Cloudfront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/auth/latest/remoteEntry.js"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
